name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run setup
      - run: mise run lint
      - run: mise run test-Builder
      - run: mise run test-tsc
